from Cost import Cross_Entropy_Back

LEARNING_RATE = 0.001

TEMPERATURE = 1

VOCAB_PATH = "./train-text.txt"
CODE_LENGTH = 3
CODE_LENGTH2 = 2 * CODE_LENGTH
ZERO = "0" * CODE_LENGTH
VOCAB_SIZE = 500
EMPTY_TOKEN = "<empty>"
UNK_TOKEN = "<unk>"

SAVE_PATH = "MING-GPT"

COST_FUNCTION_DERIVATIVE = Cross_Entropy_Back

EPSILON = 0.000000001
BETA1 = 0.9
BETA2 = 0.98

KEEP_PROB = 0.1
SMOOTHING_FACTOR = 0.001
