"""
Generated by Claude
"""


from datasets import load_dataset

from config import TRAIN_TEXT_PATH, VOCAB_PATH


MAX_BYTES = 4_000_000_000
VOCAB_MAX_BYTES = 300_000_000

ds = load_dataset("HuggingFaceFW/fineweb", "sample-10BT", split="train", streaming=True)

written = 0
vocab_written = 0
with open(TRAIN_TEXT_PATH, "w", encoding="utf-8") as text_f, open(VOCAB_PATH, "w", encoding="utf-8") as vocab_f:
    i = 0
    for row in ds:
        text = row["text"] + "\n"

        if vocab_written < VOCAB_MAX_BYTES:
            vocab_f.write(text)
            vocab_written += len(text)

        text_f.write(text)
        written += len(text)
        if written >= MAX_BYTES:
            break

        i += 1
        if i % 1000 == 0:
            print(f"Writing progress: {i}")
