"""
Generated by Claude
"""


from datasets import load_dataset

from config import ASS_TEXT_PATH
from vocabularizer import USER_TOKEN, ASS_TOKEN, STOP_TOKEN


ds = load_dataset("tatsu-lab/alpaca", split="train")

with open(ASS_TEXT_PATH, "w", encoding="utf-8") as f:
    i = 0
    for row in ds:
        user = row["instruction"]
        if row["input"]:
            user += " " + row["input"]
        f.write(f"{USER_TOKEN} {user} {ASS_TOKEN} {row['output']} {STOP_TOKEN}\n")

        i += 1
        if i % 10000 == 0:
            print(f"Writing progress: {i} rows")
